name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install Dependencies
        run: yarn install

      - name: Create Release Pull Request
        uses: changesets/action@v2
        with:
          version: yarn version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GH Package
        uses: changesets/action@v2
        with:
          registry-url: https://npm.pkg.github.com/
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
